# Generated by Django 4.0.6 on 2022-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
